# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='pytorch-summary',
    version='0.1.0',
    description='Pytorch summary (based on sksq96/pytorch-summary) which supports arbitrary inputs',
    python_requires='==3.*,>=3.8.0',
    author='Venky Iyer',
    author_email='indigoviolet@gmail.com',
    packages=['pytorch_summary', 'pytorch_summary.tests'],
    package_dir={"": "."},
    package_data={
        "pytorch_summary": [
            ".mypy_cache/3.8/*.json", ".mypy_cache/3.8/attr/*.json",
            ".mypy_cache/3.8/collections/*.json",
            ".mypy_cache/3.8/ctypes/*.json", ".mypy_cache/3.8/email/*.json",
            ".mypy_cache/3.8/http/*.json", ".mypy_cache/3.8/importlib/*.json",
            ".mypy_cache/3.8/logging/*.json",
            ".mypy_cache/3.8/multiprocessing/*.json",
            ".mypy_cache/3.8/os/*.json", ".mypy_cache/3.8/sqlite3/*.json",
            ".mypy_cache/3.8/torch/*.json",
            ".mypy_cache/3.8/torch/autograd/*.json",
            ".mypy_cache/3.8/torch/backends/*.json",
            ".mypy_cache/3.8/torch/backends/cudnn/*.json",
            ".mypy_cache/3.8/torch/cuda/*.json",
            ".mypy_cache/3.8/torch/distributed/*.json",
            ".mypy_cache/3.8/torch/distributed/autograd/*.json",
            ".mypy_cache/3.8/torch/distributions/*.json",
            ".mypy_cache/3.8/torch/jit/*.json",
            ".mypy_cache/3.8/torch/multiprocessing/*.json",
            ".mypy_cache/3.8/torch/nn/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/modules/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/qat/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/qat/modules/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/quantized/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/quantized/modules/*.json",
            ".mypy_cache/3.8/torch/nn/modules/*.json",
            ".mypy_cache/3.8/torch/nn/parallel/*.json",
            ".mypy_cache/3.8/torch/nn/qat/*.json",
            ".mypy_cache/3.8/torch/nn/qat/modules/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/dynamic/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/dynamic/modules/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/modules/*.json",
            ".mypy_cache/3.8/torch/nn/utils/*.json",
            ".mypy_cache/3.8/torch/onnx/*.json",
            ".mypy_cache/3.8/torch/optim/*.json",
            ".mypy_cache/3.8/torch/quantization/*.json",
            ".mypy_cache/3.8/torch/sparse/*.json",
            ".mypy_cache/3.8/torch/testing/*.json",
            ".mypy_cache/3.8/torch/utils/*.json",
            ".mypy_cache/3.8/torchsummary/*.json",
            ".mypy_cache/3.8/urllib/*.json"
        ],
        "pytorch_summary.tests": [
            ".mypy_cache/3.8/*.json", ".mypy_cache/3.8/attr/*.json",
            ".mypy_cache/3.8/collections/*.json",
            ".mypy_cache/3.8/ctypes/*.json", ".mypy_cache/3.8/email/*.json",
            ".mypy_cache/3.8/http/*.json", ".mypy_cache/3.8/importlib/*.json",
            ".mypy_cache/3.8/logging/*.json",
            ".mypy_cache/3.8/multiprocessing/*.json",
            ".mypy_cache/3.8/os/*.json", ".mypy_cache/3.8/sqlite3/*.json",
            ".mypy_cache/3.8/torch/*.json",
            ".mypy_cache/3.8/torch/autograd/*.json",
            ".mypy_cache/3.8/torch/backends/*.json",
            ".mypy_cache/3.8/torch/backends/cudnn/*.json",
            ".mypy_cache/3.8/torch/cuda/*.json",
            ".mypy_cache/3.8/torch/distributed/*.json",
            ".mypy_cache/3.8/torch/distributed/autograd/*.json",
            ".mypy_cache/3.8/torch/distributions/*.json",
            ".mypy_cache/3.8/torch/jit/*.json",
            ".mypy_cache/3.8/torch/multiprocessing/*.json",
            ".mypy_cache/3.8/torch/nn/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/modules/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/qat/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/qat/modules/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/quantized/*.json",
            ".mypy_cache/3.8/torch/nn/intrinsic/quantized/modules/*.json",
            ".mypy_cache/3.8/torch/nn/modules/*.json",
            ".mypy_cache/3.8/torch/nn/parallel/*.json",
            ".mypy_cache/3.8/torch/nn/qat/*.json",
            ".mypy_cache/3.8/torch/nn/qat/modules/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/dynamic/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/dynamic/modules/*.json",
            ".mypy_cache/3.8/torch/nn/quantized/modules/*.json",
            ".mypy_cache/3.8/torch/nn/utils/*.json",
            ".mypy_cache/3.8/torch/onnx/*.json",
            ".mypy_cache/3.8/torch/optim/*.json",
            ".mypy_cache/3.8/torch/quantization/*.json",
            ".mypy_cache/3.8/torch/sparse/*.json",
            ".mypy_cache/3.8/torch/testing/*.json",
            ".mypy_cache/3.8/torch/utils/*.json",
            ".mypy_cache/3.8/torchsummary/*.json",
            ".mypy_cache/3.8/torchsummary/tests/*.json",
            ".mypy_cache/3.8/urllib/*.json"
        ]
    },
    install_requires=[
        'attrs==19.*,>=19.3.0', 'pytest==5.*,>=5.4.3', 'tabulate==0.*,>=0.8.7',
        'torch==1.*,>=1.5.1'
    ],
)
